# Generated by Django 2.2 on 2021-07-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0004_auto_20210703_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='desc',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='String', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=45),
        ),
    ]
