# Generated by Django 2.2.5 on 2021-07-17 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E2BlackApp', '0002_books_users_who_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='user_who_grants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_granted', to='E2BlackApp.User'),
        ),
    ]
