# Generated by Django 2.2.5 on 2021-07-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0002_auto_20210716_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='users_who_grant',
            field=models.ManyToManyField(related_name='granted_books', to='ExamApp.User'),
        ),
    ]
