# Generated by Django 2.2.5 on 2021-07-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0004_books_granted_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='granted_wish',
            field=models.BooleanField(),
        ),
    ]
