# Generated by Django 2.2.5 on 2021-07-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0005_auto_20210716_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='granted_wish',
            field=models.BooleanField(default=False),
        ),
    ]
