# Generated by Django 2.2.5 on 2021-07-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0006_auto_20210716_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='granted_wish',
            field=models.BooleanField(),
        ),
    ]
