# Generated by Django 2.2.5 on 2021-07-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewerApp', '0003_auto_20210715_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='author',
            field=models.CharField(default='Something', max_length=255),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(default='Something', max_length=255),
        ),
    ]
