# Generated by Django 2.2.5 on 2021-07-15 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewerApp', '0004_auto_20210715_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='review',
        ),
        migrations.AddField(
            model_name='reviews',
            name='text',
            field=models.CharField(default='Robert', max_length=255),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='author',
            field=models.CharField(default='Text', max_length=255),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='BeltReviewerApp.User'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(default='Robert', max_length=255),
        ),
    ]
