# Generated by Django 2.2.5 on 2021-07-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_review_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Robert', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Johnson', max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='kuyperhouse@gmail.com', max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=45),
        ),
    ]
