# Generated by Django 2.2.5 on 2021-07-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewer3App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='text',
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='reviews',
            name='review',
            field=models.CharField(default='Review', max_length=255),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(default='Title', max_length=255),
        ),
    ]
