# Generated by Django 2.2.5 on 2021-07-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewer3App', '0002_auto_20210715_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('author', models.CharField(default='Text', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='title',
        ),
    ]
