# Generated by Django 2.2.5 on 2021-07-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewer3App', '0004_auto_20210715_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
