# Generated by Django 2.2 on 2021-07-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SemiRestfulTvShowsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
