# Generated by Django 2.2.5 on 2021-07-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='granted_wish',
            field=models.BooleanField(default=False),
        ),
    ]
