# Generated by Django 2.2.5 on 2021-07-17 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0002_auto_20210716_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='users_who_grant',
        ),
        migrations.AddField(
            model_name='books',
            name='user_who_grants',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish_granted', to='Eapp.User'),
        ),
    ]
