# Generated by Django 2.2.5 on 2021-07-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FavoriteBooksApp4App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.CharField(default='Text', max_length=255),
        ),
    ]
