# Generated by Django 2.2.5 on 2021-07-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BJapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizard',
            name='year',
            field=models.IntegerField(default=3),
        ),
    ]
