# Generated by Django 2.2.5 on 2021-07-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FavoriteBooksApp3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall_message',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_books', to='FavoriteBooksApp3.User'),
        ),
    ]
